<a href="https://colab.research.google.com/github/abhiamishra/ClassificationPractice/blob/main/ClassificationPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Building a pitch classifying model with Python

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('TrainingDataset.csv',encoding='latin-1')
dataset['identifier']= np.where(dataset['pos']=="DL", 1, 0)
X = dataset.iloc[:, 1:-2].values
y = dataset.iloc[:, -2].values

In [ ]:
dataset

name        x       y  ...        area  identifier  pos
0        Enis Bardhi  62.3700  48.756  ...  1790.50851           0   ML
1       José Campaña  56.2800  45.152  ...  1771.24122           0   MC
2     Gonzalo Melero  48.7200  38.964  ...  1271.49120           0   MC
3     Sergio Postigo  31.7625  29.920  ...  1238.55438           0   DC
4               Toño  45.7275  62.764  ...   921.59550           1   DL
...              ...      ...     ...  ...         ...         ...  ...
2198   André Ramalho  34.8600  22.712  ...   688.32456           0   DC
2199   Joakim Maehle  52.8150   6.052  ...   500.81031           0   DR
2200     Jhon Lucumí  28.4550  49.164  ...   294.96411           0   DC
2201   Gaetan Coucke  10.8675  32.232  ...   141.89322           0   GK
2202      Papu Gómez  71.2425  52.020  ...   816.96951           0  AMC

[2203 rows x 8 columns]

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
print(X_train)

[[  55.86      29.648     60.27      30.736   1269.43131]
 [  32.55      25.84      43.575     27.676    830.43555]
 [  48.615     62.152     60.375     58.14     501.98127]
 ...
 [  69.9825    36.142     71.085     34.952   1345.22241]
 [  68.46      12.648     69.405     18.768   1180.48833]
 [   9.555     32.98      29.925     33.524    157.31562]]


In [ ]:
print(y_train)

[0 0 1 ... 0 0 0]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Training the Naive Bayes model on the Training set

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

## Predicting the Test set results

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[500  18]
 [  5  28]]


0.9582577132486388

# Testing on Dortmund's 2019/20 dataset:

In [ ]:
dortmund_data = pd.read_csv('TestData.csv',encoding='latin-1')
dortmund_test = dortmund_data.iloc[:, 1:-1].values
dortmund_players = dortmund_data.iloc[:, 0].values

In [ ]:
dortmund_feat = sc.transform(dortmund_test)

In [ ]:
print(dortmund_players)

['Nico Schulz' 'Lukasz Piszczek' 'Paco Alc<e1>cer' 'Marco Reus'
 'Julian Weigl' 'Jadon Sancho' 'Manuel Akanji' 'Mats Hummels'
 'Axel Witsel' 'Thorgan Hazard' 'Marwin Hitz' 'Achraf Hakimi'
 'Julian Brandt' 'Mario G<f6>tze' 'Roman B<fc>rki' 'Thomas Delaney'
 'Mahmoud Dahoud' 'Raphael Guerreiro' 'Dan-Axel Zagadou'
 'Leonardo Balerdi' 'Erling Haaland' 'Giovanni Reyna' 'Emre Can'
 'Mateu Morey']


In [ ]:
dortmund_predictions = classifier.predict(dortmund_feat)
print(np.concatenate((dortmund_players.reshape(len(dortmund_players),1), 
                      dortmund_predictions.reshape(len(dortmund_predictions),1)),1))

[['Nico Schulz' 1]
 ['Lukasz Piszczek' 0]
 ['Paco Alc<e1>cer' 0]
 ['Marco Reus' 0]
 ['Julian Weigl' 0]
 ['Jadon Sancho' 0]
 ['Manuel Akanji' 0]
 ['Mats Hummels' 0]
 ['Axel Witsel' 0]
 ['Thorgan Hazard' 0]
 ['Marwin Hitz' 0]
 ['Achraf Hakimi' 0]
 ['Julian Brandt' 0]
 ['Mario G<f6>tze' 0]
 ['Roman B<fc>rki' 0]
 ['Thomas Delaney' 0]
 ['Mahmoud Dahoud' 0]
 ['Raphael Guerreiro' 1]
 ['Dan-Axel Zagadou' 1]
 ['Leonardo Balerdi' 0]
 ['Erling Haaland' 0]
 ['Giovanni Reyna' 0]
 ['Emre Can' 0]
 ['Mateu Morey' 0]]
